# Generated by Django 4.0.4 on 2022-04-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPUdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core1', models.FloatField(blank=True, default=None, null=True)),
                ('core2', models.FloatField(blank=True, default=None, null=True)),
                ('core3', models.FloatField(blank=True, default=None, null=True)),
                ('core4', models.FloatField(blank=True, default=None, null=True)),
                ('cpuSpeed', models.FloatField(blank=True, default=None, null=True)),
                ('ramUsage', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
