# Generated by Django 4.0.4 on 2022-04-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpudata',
            name='core1',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpudata',
            name='core2',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpudata',
            name='core3',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpudata',
            name='core4',
            field=models.CharField(default=4, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpudata',
            name='cpuSpeed',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpudata',
            name='ramUsage',
            field=models.CharField(default=6, max_length=20),
            preserve_default=False,
        ),
    ]
